apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    argocd-autopilot.argoproj-labs.io/default-dest-server: https://kubernetes.default.svc
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/sync-wave: "-2"
  creationTimestamp: null
  name: apps-monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: apps-monitoring project
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: apps-monitoring
  namespace: argocd
spec:
  generators:
    - git:
        files:
          - path: apps/apps-monitoring/**/config.json
        repoURL: https://github.com/florianspk/argocd-apps-homelab.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""
  syncPolicy: {}
  template:
    metadata:
      name: "{{ appName }}"
      namespace: argocd
      labels:
        app.kubernetes.io/managed-by: argocd-autopilot
        app.kubernetes.io/name: "{{ appName }}"
    spec:
      project: default
      destination:
        server: "{{ destServer }}"
        namespace: "{{ destNamespace }}"
      sources:
        - repoURL: "{{ chartRepoURL }}"
          chart: "{{ chart }}"
          targetRevision: "{{ chartVersion }}"
          helm:
            valueFiles:
              - $values/{{ valuesPath }}
        - repoURL: "{{ valuesGitRepo }}"
          targetRevision: "{{ valuesGitRef }}"
          ref: values
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
status: {}
---
# To add annotation pod-security.kubernetes.io/enforce: privileged
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
