apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb-tls-secret
spec:
  commonName: influxdb server
  dnsNames:
    - influxdb.wheezy.lab
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: influxdb-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
