apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  labels:
    app: kavita
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      initContainers:
        - name: create-user
          image: busybox:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "kavita:x:1000:1000:Kavita User:/home/kavita:/bin/sh" >> /etc/passwd
              echo "kavita:x:1000:" >> /etc/group
              mkdir -p /home/kavita
              chown 1000:1000 /home/kavita
          securityContext:
            runAsUser: 0
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: kavita
          image: linuxserver/kavita:0.8.6
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: kavita-config
                  key: TZ
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: kavita-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: kavita-config
                  key: PGID
          volumeMounts:
            - name: kavita-config
              mountPath: /kavita/config
            - name: servarr-media
              mountPath: /media/books
              subPath: books
            - name: servarr-media
              mountPath: /media/downloads
              subPath: downloads
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: kavita-config
          persistentVolumeClaim:
            claimName: kavita-config-pvc
        - name: servarr-media
          persistentVolumeClaim:
            claimName: servarr-jellyfin-media
      restartPolicy: Always
