# PersistentVolumeClaim pour les données de configuration
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config-pvc
  labels:
    app: kavita
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: linstor-lvm-r1
