apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: track-litlyx
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/forwarded-for-header: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/real-ip-header: "X-Real-IP"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/enable-real-ip: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
spec:
  ingressClassName: ingress-public
  rules:
    - host: "track.florianspk.fr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litlyx-producer
                port:
                  number: 3099
