apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
spec:
  project: apps-ops
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: ghost
    # renovate: datasource=helm depName=ghost registryUrl=https://charts.bitnami.com/bitnami
    targetRevision: "22.1.15"
    helm:
      valueFiles:
        - $values/ops/ghost/values.yaml
  - repoURL: 'https://github.com/florianspk/values-apps.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true