apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-tls-secret
spec:
  commonName: auth server
  dnsNames:
    - "auth.wheezy.lab"
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: auth-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
