apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-oauth-public
spec:
  ingressClassName: ingress-public
  rules:
    - host: auth.wheezy.fr
      http:
        paths:
          - path: /application/o/
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
          - path: /source/oauth/callback/
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
          - path: /media/
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
