apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-tls-secret
spec:
  commonName: uptime-kuma server
  dnsNames:
    - uptime.wheezy.lab
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: uptime-kuma-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
