apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: observability-pvc-daily
  namespace: velero
spec:
  schedule: "0 1 * * *"
  template:
    defaultVolumesToFsBackup: false
    snapshotMoveData: true
    includedNamespaces:
      - observability
    ttl: 168h0m0s
