apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdata
  namespace: argocd
spec:
  project: monitoring
  sources:
  - repoURL: https://helm.influxdata.com/
    chart: influxdb
    targetRevision: "4.*"
    helm:
      valueFiles:
        - $values/monitoring/influxdata/values.yaml
  - repoURL: 'https://github.com/florianspk/values-apps.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true