apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc-secret
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAYyRPE0koRemVXuNdfB6TngJzh0N0hYerTPQlxM2ZA7cI6rGJHmWZR9vZvfPHqZfD6aXfzWTVHa3e5n0pibutgIWUGyLDCDOB/kTQlJnJEVAUIsokpUyLoQV8KjA06U7ow/37vQ7JBVclS8539dVb1IGXY19LB0TkRHrlfjz8lawr/obVQoLq29l88YUOJbf8RV1jJ0AGGsY4HFaMnLAdIBbwnDCVKyH2T0M2KdBTSPAxOZkLJSvEI5TFsvd3Ih22n1/3jux0Rgh2RCq+e6UtpJ3NjqzQueMCc+vhFKMYK9GoN3NJORkd/rKpMPQe8ZnPLKxvb3/9ad0GDfyBB8UKy0i7TReibZJlYxV99bkOt56/JD4nsMiiT37BjF+ZJZjQXYcEUbP3GCLBB4Iv9eZOUAkRlNjN7XPAqQKavU/B87sKr2qq3GG3Lv6T1qQCpsxzPZq6a4Z6UB8C87S040scpfMGf1ESKL+vnTCMfnMh80hzMa55b0kgzsFV6m7/jtY1gqow7bQ1inkvEQrgV/Quwhq9qrs6rSDYW0pETJPGVu3I54hm9m5nhflTtBwBzwdWIN/WdHCVJR9gqsH6FEioXwMRwaXdY3tZKZQvycGU2eneiMZMnPg7RPDd0RENRWZXfuDeQDSMVXDBCa1YoDIlzDR6eUtwY9yuiyaz+7CoOWm5tBIefPkq5h++swjux1rOV5SiRYTvu3DAbSlLyQADpZjCzRyMA1A6cxXlCJqPDAOs89Gx7sS8xXT3mCR+U0TcpBaoqq9UhBK6te/9lkWv+w6b3Gi+1nk/paQD2yieaNJVPRdCOZsy8XwE0V3xxymy6BnyHt1InksKOIrvnF465ULnKdrUGMwOUELTFyaE/Aw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc-secret
      namespace: observability
