apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oidc-secret
  namespace: observability
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAwXWHlmSZI+WJPY/u3BxiCR78nwWDmHaubHcSmXnE2aMBZjYTCOphK69aHyk7yki6bWmXihjxHpZitAgQEN1iZ815EhiMpqzUTZaNzRrBFZMPCo77YDkbMyJMtKwcKKI94UpJjO2CPma/Alb0zzNAcoXSHCHEIIcaf9uL/hqP/UwIz0ZEIMZ1t0NUZqC83KVI4OghuS8m8yCzeZKX4ChIMdiJmUpcPEtv0WyfvyW9fR/Ih45rZdy7YRzZrDC6Dy0e6xmUyMArajiAogo3mfOwLzozHgL7isPPYenZ8/u21m4G2y6ZxZCJpg5Fj0VixT8o7tRYKUtw5+nF/xCX41O023/Zz8vsFMu4rqB5EYcsL0IwTvhlxR7ELQ4rZpwvJExu3uXUciOdkOTjL+R4XWszQoGky5+gL+RHyZyrQvjwAzOPbF26Qj2fBUCx9Ur5x/3zIfmXgxfvVI2hugylTxFpdawGmozBTVyAPLq3YKa47KXCP31gbiu0UAwXmtXTukt+6MKMyFwAArn4hG6kYaVeuC5JKnlhOI0L5md/wf9uKMazAl1JTETT1tV7EGwLl+jGawO5qXOW9a0F/2/yMmeEeTTdNno07WajuCLNHIQ1uTBXh9pytmln6KbikllYnkfL027sHt8xImkbVeh9k90HfpKLURsfUBzSnEEHh1n2XsooWI3+qXk2eSJUM2bGOTQs5nON/j1nP0VSTg0BSR8kEFlETAGAAiR1wJYg2VYp4TlxYvyGwnvmkgVqB4K6XPW6ojz1KAcl/gWrKUuzMhPfFpjoqtIW69M9lltEF+OnhbJ/+JfXMeFVOSPKwenxHnTGfujfhGiXz6LxRZPb0ZWsKtMFD/2x6K7fmXyBFTSNvGA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oidc-secret
      namespace: observability

