apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls-secret
spec:
  commonName: homepage server
  dnsNames:
    - hub.wheezy.lab
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: homepage-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
