apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
  labels:
    app: kromgo
data:
  config.yaml: |
    metrics:
      - name: cluster_cpu_usage
        query: 'round((1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100, 0.1)'
        suffix: '%'
      - name: cluster_memory_usage
        query: 'round((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100, 0.1)'
        suffix: '%'
      - name: cluster_pods_running
        query: 'sum(kube_pod_status_phase{phase="Running"})'
      - name: cluster_nodes_ready
        query: 'sum(kube_node_status_condition{condition="Ready",status="true"})'
      - name: kubelet_version
        query: 'kube_node_info{job="kube-state-metrics"}'
        label: 'kubelet_version'
      - name: talos_version
        query: 'kube_node_info{job="kube-state-metrics"}'
        label: 'os_image'
      - name: kernel_version
        query: 'kube_node_info{job="kube-state-metrics"}'
        label: 'kernel_version'
