apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
  labels:
    app: kromgo
data:
  config.yaml: |
    server:
      port: 8080
      cors:
        enabled: true
        origins: ["*"]

    prometheus:
      url: "http://kube-prometheus-stack-prometheus.default.svc.cluster.local:9090"

    metrics:
      - name: cluster_cpu_usage
        query: 'round((1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100, 0.1)'
        suffix: '%'
        color: 'blue'

      - name: cluster_memory_usage
        query: 'round((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100, 0.1)'
        suffix: '%'
        color: 'green'

      - name: cluster_pods_running
        query: 'sum(kube_pod_status_phase{phase="Running"})'
        suffix: ''
        color: 'orange'

      - name: cluster_nodes_ready
        query: 'sum(kube_node_status_condition{condition="Ready",status="true"})'
        suffix: ''
        color: 'purple'

      - name: cluster_disk_usage
        query: 'round(avg((node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_avail_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100, 0.1)'
        suffix: '%'
        color: 'red'

      - name: cluster_uptime_days
        query: 'round((time() - node_boot_time_seconds) / 86400, 0.1)'
        suffix: ' days'
        color: 'brightgreen'
