apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: n8n-pvc-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      - n8n
    ttl: 168h0m0s
