apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: n8n-pvc-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - n8n
    includedResources:
      - persistentvolumeclaims
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: n8n
    ttl: 168h0m0s
