apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: n8n-pvc-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
      - n8n
    includedResources:
      - persistentvolumeclaims
      - volumesnapshots
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: n8n
    snapshotVolumes: true
    volumeSnapshotLocations:
      - n8n-pvc
    ttl: 720h0m0s
