apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls-secret
spec:
  commonName: n8n server
  dnsNames:
    - "n8n.wheezy.lab"
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: n8n-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
