apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls-secret
spec:
  commonName: nextcloud server
  dnsNames:
    - "*.wheezy.lab"
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: nextcloud-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
