apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-registry
  namespace: wheezy-blog
spec:
  encryptedData:
    .dockerconfigjson: AgDFYsAUBwblABMlHIR4/qU1d4lXenGIhJJ8LTbEP5r8CZ+6MwSHoU+YsGfgeYLuV3l/NXAeS13Rww6y3x077MDiuvvY8eSqUZP2wWHTljx9y4+05mKXEyywyBrpq8M3Dl3xPcELx/jM5MLlwrcXf1ssU0TpGQUucePBwNmmx2TlSlVlZ7XNL4GqCsgeJKU8yu7vrPWOowXaMkbYb89emltJIACMSs7T90QIL71aHUoMi2APo08EtckSVWaagk6DkozXtW3UB1KrxHyTRmAbcT8HM/kEZJs9q2JU0V9IxobBl5hCgNYW90JbaIT9pa+v35b/Ah7ODxWnsb41c5qBD9rJ8vBd1sY1pNkFW53ok8YcakBpX+Ex5epufduGkb+grROG/fzN9pds7Wb1j32bgkEjqgaVECRPOFvqxZPn4azGg78nzAFs4AO97B41AL1dCAERNfkkGB6ZNPsAWNheu5/WzhfoyNvViCobxtmpFcx+Dg5m8jDXIu9eDjhhxUOqJUWMWHEh8Gfu6mhXyk9QlSQ065aFfFBwvnU5obQrrhaRTooXe3qbPx1dFE+QqUNWkuuigacQSIRBijzLOFwmJuWIEOS/QtwE0dqPd20lZFLFNJlea7TNa8+zVo8pmELlOvmjQphCLbhPYij0c9WVV7SLHBtMa0xM3KPSX5fPPCBjQ8mCdXu2IjQGujJ1yuz7ZDPvqLWT7k5+pSh1BnAdkzqT2iPxNIEM+rUMD3obg0hM4N0nGiQ7UoYFSxjdsMoMP3Siitk8w5UkaZwI62nRm71tJK6mRzle2BLR3z0d9XhQb4j5N5KMletbGw3mpuJD7miP7qEviCnWafM6lbXkwiJh9ipOg4nDjg==
  template:
    metadata:
      creationTimestamp: null
      name: github-registry
      namespace: wheezy-blog
    type: kubernetes.io/dockerconfigjson
