# prometheus-instance.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1

  retention: 15d
  retentionSize: 28GB

  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: linstor-lvm-r1
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi

  # ServiceMonitors à collecter (tous les namespaces)
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  # PodMonitors
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  # RBAC
  serviceAccountName: prometheus
