apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: alloy-all-logs
  namespace: observability
spec:
  controller:
    type: daemonset
    tolerations:
      - effect: NoSchedule
        operator: Exists
  alloy:
    mounts:
      varlog: true
    configMap:
      content: |-
        // Discovery de tous les pods
        discovery.kubernetes "pods" {
          role = "pod"
        }

        // Relabeling : path vers les fichiers + labels utiles
        discovery.relabel "pod_logs" {
          targets = discovery.kubernetes.pods.targets

          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            target_label  = "namespace"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_name"]
            target_label  = "pod"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_container_name"]
            target_label  = "container"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
            target_label  = "app"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
            separator     = "/"
            replacement   = "/var/log/pods/*$1/*.log"
            target_label  = "__path__"
          }
        }

        // Lecture des logs via l'API K8s (stdout/stderr)
        loki.source.kubernetes "pod_logs" {
          targets    = discovery.relabel.pod_logs.output
          forward_to = [loki.process.pod_logs.receiver]
        }

        // Ajout du label cluster
        loki.process "pod_logs" {
          stage.static_labels {
            values = {
              cluster = "wheezylab",
            }
          }
          forward_to = [loki.write.loki.receiver]
        }

        // Envoi vers Loki
        loki.write "loki" {
          endpoint {
            url = "http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push"
          }
        }
