apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance
spec:
  parentRefs:
    - name: internal-gateway
      namespace: kube-system
      sectionName: https
  hostnames:
    - "glance.wheezy.lab"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: glance
          port: 8080
          weight: 100
