apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-tls-secret
spec:
  commonName: Alertmanager server
  dnsNames:
    - alertmanager.wheezy.lab
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: alertmanager-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
