apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-secret
spec:
  commonName: Grafana server
  dnsNames:
    - grafana.wheezy.lab
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: grafana-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
