apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-secret
spec:
  commonName: Prometheus server
  dnsNames:
    - prometheus.wheezy.lab
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: prometheus-server-tls
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
