apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-asssistant
  namespace: argocd
spec:
  project: apps-ops
  sources:
  - repoURL: http://pajikos.github.io/home-assistant-helm-chart
    chart: home-asssistant
    # renovate: datasource=helm depName=home-assistant registryUrl=http://pajikos.github.io/home-assistant-helm-chart
    targetRevision: "0.2.109"
    helm:
      valueFiles:
        - $values/apps-ops/home-assistant/values.yaml
  - repoURL: 'https://github.com/florianspk/values-apps.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: home-asssistant
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true