apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: immich-pvc-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      - immich
    includedResources:
      - persistentvolumeclaims
    ttl: 168h0m0s
