apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stirling-pdf-tls
spec:
  commonName: stirling-pdf
  dnsNames:
    - "tools.wheezy.lab"
  duration: 4320h
  issuerRef:
    kind: ClusterIssuer
    name: ingress
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: stirling-pdf
  subject:
    organizationalUnits:
      - Kubernetes
    organizations:
      - wheezy.lab
